/**
 * get authenticate token
 */
export const INPUT_ACCOUNT_PHONE = 'INPUT_ACCOUNT_PHONE'
export const INPUT_ACCOUNT_PASSWORD = 'INPUT_ACCOUNT_PASSWORD'
export const GET_TOKEN_START = 'GET_TOKEN_START'
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
/**
 * message manage
 */
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
/**
 * frontend category
 */
export const GET_FRONTEND_CATEGORY_START = 'GET_FRONTEND_CATEGORY_START'
export const GET_FRONTEND_CATEGORY_FAIL = 'GET_FRONTEND_CATEGORY_FAIL'
export const GET_FRONTEND_CATEGORY_SUCCESS = 'GET_FRONTEND_CATEGORY_SUCCESS'
/**
 * property
 */
export const GET_PROPERTY_START = 'GET_PROPERTY_START'
export const GET_PROPERTY_FAIL = 'GET_PROPERTY_FAIL'
export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS'
/**
 * create product
 */
export const SELECT_PRODUCT_FRONTEND_CATEGORY = 'SELECT_PRODUCT_FRONTEND_CATEGORY'
export const INPUT_PRODUCT_NAME = 'INPUT_PRODUCT_NAME'
export const INPUT_PRODUCT_DESCRIPTION = 'INPUT_PRODUCT_DESCRIPTION'
export const SELECT_PRODUCT_PROPERTY = 'SELECT_PRODUCT_PROPERTY'
export const CHECK_PRODUCT_PROPERTY_VALUE = 'CHECK_PRODUCT_PROPERTY_VALUE'
export const INPUT_SKU_NAME = 'INPUT_SKU_NAME'
export const INPUT_SKU_BARCODE = 'INPUT_SKU_BARCODE'
export const INPUT_SKU_PRICE = 'INPUT_SKU_PRICE'
export const INPUT_SKU_SELL_UNIT = 'INPUT_SKU_SELL_UNIT'
export const INPUT_SKU_STOCK = 'INPUT_SKU_STOCK'
export const CHECK_SKU_SELL_STATE = 'CHECK_SKU_SELL_STATE'
export const UPLOAD_SKU_IMAGE = 'UPLOAD_SKU_IMAGE'
