/**
 * get authenticate token
 */
export const INPUT_ACCOUNT_PHONE = 'INPUT_ACCOUNT_PHONE'
export const INPUT_ACCOUNT_PASSWORD = 'INPUT_ACCOUNT_PASSWORD'
export const GET_TOKEN_START = 'GET_TOKEN_START'
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'

/**
 * destory token
 */
export const DESTORY_TOKEN = 'DESTORY_TOKEN'

/**
 * message manage
 */
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
/**
 * frontend category
 */
export const GET_FRONTEND_CATEGORY_START = 'GET_FRONTEND_CATEGORY_START'
export const GET_FRONTEND_CATEGORY_FAIL = 'GET_FRONTEND_CATEGORY_FAIL'
export const GET_FRONTEND_CATEGORY_SUCCESS = 'GET_FRONTEND_CATEGORY_SUCCESS'
/**
 * property
 */
export const GET_PROPERTY_START = 'GET_PROPERTY_START'
export const GET_PROPERTY_FAIL = 'GET_PROPERTY_FAIL'
export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS'
/**
 * create product
 */
export const SELECT_PRODUCT_FRONTEND_CATEGORY = 'SELECT_PRODUCT_FRONTEND_CATEGORY'
export const INPUT_PRODUCT_NAME = 'INPUT_PRODUCT_NAME'
export const INPUT_PRODUCT_DESCRIPTION = 'INPUT_PRODUCT_DESCRIPTION'
export const SELECT_PRODUCT_PROPERTY = 'SELECT_PRODUCT_PROPERTY'
export const CHECK_PRODUCT_PROPERTY_VALUE = 'CHECK_PRODUCT_PROPERTY_VALUE'
export const INPUT_SKU_NAME = 'INPUT_SKU_NAME'
export const INPUT_SKU_BARCODE = 'INPUT_SKU_BARCODE'
export const INPUT_SKU_PRICE = 'INPUT_SKU_PRICE'
export const INPUT_SKU_SELL_UNIT = 'INPUT_SKU_SELL_UNIT'
export const INPUT_SKU_STOCK = 'INPUT_SKU_STOCK'
export const CHECK_SKU_SELL_STATE = 'CHECK_SKU_SELL_STATE'
export const UPLOAD_SKU_IMAGE = 'UPLOAD_SKU_IMAGE'
export const DELETE_SKU = 'DELETE_SKU'
export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'

/**
 * get product list
 */
export const GET_PRODUCT_LIST_START = 'GET_PRODUCT_LIST_START'
export const GET_PRODUCT_LIST_FAIL = 'GET_PRODUCT_LIST_FAIL'
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS'

/**
 * edit sku
 */
export const MODIFY_SKU_START = 'MODIFY_SKU_START'
export const MODIFY_SKU_FAIL = 'MODIFY_SKU_FAIL'
export const MODIFY_SKU_SUCCESS = 'MODIFY_SKU_SUCCESS'

/**
 * get order list
 */
export const GET_ORDER_LIST_START = 'GET_ORDER_LIST_START'
export const GET_ORDER_LIST_FAIL = 'GET_ORDER_LIST_FAIL'
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'

/**
 * get order information
 */
export const GET_ORDER_INFORMATION_START = 'GET_ORDER_INFORMATION_START'
export const GET_ORDER_INFORMATION_FAIL = 'GET_ORDER_INFORMATION_FAIL'
export const GET_ORDER_INFORMATION_SUCCESS = 'GET_ORDER_INFORMATION_SUCCESS'

/**
 * get product
 */
export const GET_PRODUCT_START = 'GET_PRODUCT_START'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

/**
 * edit product
 */
export const MODIFY_PRODUCT_FRONTEND_CATEGORY = 'MODIFY_PRODUCT_FRONTEND_CATEGORY'
export const MODIFY_PRODUCT_NAME = 'MODIFY_PRODUCT_NAME'
export const MODIFY_PRODUCT_DESCRIPTION = 'MODIFY_PRODUCT_DESCRIPTION'
export const MODIFY_PRODUCT_SKU_NAME = 'MODIFY_PRODUCT_SKU_NAME'
export const MODIFY_PRODUCT_SKU_BARCODE = 'MODIFY_PRODUCT_SKU_BARCODE'
export const MODIFY_PRODUCT_SKU_PRICE = 'MODIFY_PRODUCT_SKU_PRICE'
export const MODIFY_PRODUCT_SKU_SELL_UNIT = 'MODIFY_PRODUCT_SKU_SELL_UNIT'
export const MODIFY_PRODUCT_SKU_STOCK = 'MODIFY_PRODUCT_SKU_STOCK'
export const MODIFY_PRODUCT_SKU_SELL_STATE = 'MODIFY_PRODUCT_SKU_SELL_STATE'
export const MODIFY_PRODUCT_SKU_IMAGE = 'MODIFY_PRODUCT_SKU_IMAGE'
export const MODIFY_PRODUCT_START = 'MODIFY_PRODUCT_START'
export const MODIFY_PRODUCT_FAIL = 'MODIFY_PRODUCT_FAIL'
export const MODIFY_PRODUCT_SUCCESS = 'MODIFY_PRODUCT_SUCCESS'
export const CANCEL_PRODUCT_MODIFY = 'CANCEL_PRODUCT_MODIFY'

